theme: jekyll-theme-slate
title: DevOps au quotidien
email: noel@bardelot.fr
description: >
  Un journal de bord DevOps, avec des réflexions sur l'automatisation, l'humain, et les outils informatiques.
url: "http://blog.bardelot.fr"
github_username:  NBardelot
timezone: Europe/Paris
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
exclude: README.md